# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            数据挖掘
tagline:          '数据挖掘课程主页'
description:      '<p>上课时间：周一5~6节</p><p>上课地点：教七502</p>'
url:              http://zcwang.org/datamining2016
baseurl:          /datamining2016
# baseurl:          /

author:
  name:           'Zhichun Wang'
  url:            http://zcwang.org

# paginate:         5

# Custom vars
version:          2.1.0

# github:
  # repo:           https://github.com/poole/hyde

gems:
- jekyll-gist
- jekyll-paginate

paginate: 5
paginate_path: "page:num"
